name: Add Issue to Project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: Add issue to GitHub Project and set status
        uses: github/add-to-project@v1
        with:
          project-url: https://github.com/users/Wectornanime/projects/1
          github-token: ${{ secrets.MY_PAT }}
          fields: |
            Status=Backlog
